name: Deploy APP

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

        # Install latest LTS Node.js
        # Also installs yarn
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependecies
        run: |
          yarn install

      - name: Build App with Standard Webpack/Babel Setup
        run: |
          yarn build

      - name: Deploy to cheap-ear.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "cheap-ear.surge.sh"
          project: "./dist"
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
